### ISSUE TITLE
CieloEcommerce.captureSale retorna vazio

### ISSUE THREAD

**Issue by fkaizo** [DeveloperCielo/API-3.0-Java#13]
public Sale captureSale(String paymentId, Integer amount, Integer serviceTaxAmount){...}

Só me retorna um Sale vazio. 
Como pego o retorno da chamada?

No log aparece esse retorno, mas não chega nada no obj.
`{
   "Status":2,
   "ReasonCode":0,
   "ReasonMessage":"Successful",
   "ProviderReturnCode":"6",
   "ProviderReturnMessage":"Operation Successful",
   "ReturnCode":"6",
   "ReturnMessage":"Operation Successful",
   "Links":[
      {
         "Method":"GET",
         "Rel":"self",
         "Href":"https://apiquerysandbox.cieloecommerce.cielo.com.br/1/sales/50411394-0b3d-49b0-adb2-711bf41b8b9b"
      },
      {
         "Method":"PUT",
         "Rel":"void",
         "Href":"https://apisandbox.cieloecommerce.cielo.com.br/1/sales/50411394-0b3d-49b0-adb2-711bf41b8b9b/void"
      }
   ]
}`

**Comment by netojoaobatista** [comment]
Deveria estar retornando a instância; como está sua chamada?

**Comment by fkaizo** [comment]
Retorna uma instancia nula.
estou fazendo a chamada do exemplo: 
`// Com o ID do pagamento, podemos fazer sua captura, se ela não tiver sido capturada ainda
    sale = new CieloEcommerce(merchant, Environment.SANDBOX).captureSale(paymentId, 15700, 0);`

![image](https://cloud.githubusercontent.com/assets/15651433/24574962/1c1de336-1671-11e7-871f-19259bac2504.png)
