### ISSUE TITLE
Erros em compra com cartão de crédito #2

### ISSUE THREAD

**Issue by fernandohls** [DeveloperCielo/API-3.0-Java#15]
Boa tarde!!!

Estou implementando a integração com a API 3.0 em Java, porém estou com alguns probleminhas e preciso de ajuda...

Já enviei o formulário de homologação do Cielo e-Commerce, porém toda requisição que faço obtenho o retorno "184 - Request could not be empty", mesmo em sandbox...

Vi um issue de um problema parecido com o meu que acontecia em produção.

Obrigado!

**Comment by fkaizo** [comment]
@fernandohls Compartilha teu request.

**Comment by fernandohls** [comment]
@fkaizo leve "ContratoPagamento" como uma possível lista de cartões para uma única compra.

`Merchant merchant = new Merchant(MERCHANT_ID, MERCHANT_KEY);

		for (ContratoPagamento contratoPagamento : contrato.getContratoPagamentoList()) {
			if (contrato.getStatus() == Contrato.STATUS_CONFIRMADO) {
				Sale sale = new Sale(contratoPagamento.getId());
				Customer customer = new Customer(contrato.getCompradorNome());
				customer.setEmail(contrato.getCompradorEmail());
				sale.setCustomer(customer);
				String amountS = TrataNumero.numeroPuro(String.valueOf(dF.format(contratoPagamento.getValor())));
				Integer amountI = Integer.parseInt(amountS);
				Payment payment = new Payment(amountI);
				payment.setInstallments(contratoPagamento.getNumeroParcelas());
				payment.setType(Type.CreditCard);
				payment.setProvider(Provider.Simulado);
				CreditCard creditCard = new CreditCard(contratoPagamento.getCodigoSegurancaCartao(), contratoPagamento.getBandeiraCartao());
				creditCard.setCardNumber(contratoPagamento.getNumeroCartao());
				creditCard.setBrand(contratoPagamento.getBandeiraCartao());
				creditCard.setExpirationDate(contratoPagamento.getValidadeCartao());
				creditCard.setHolder(contratoPagamento.getNomeTitularCartao());
				creditCard.setSecurityCode(contratoPagamento.getCodigoSegurancaCartao());
				payment.setCreditCard(creditCard);
				sale.setPayment(payment);
				try {
					Sale saleReturned = new CieloECommerce(merchant).createSale(sale);
					// SE O PAGAMENTO NÃO FOI EFETUADO (NÃO ESTÁ APTO PARA SER CAPTURADO)
					if (saleReturned.getPayment().getPaymentId() != null && !saleReturned.getPayment().getPaymentId().trim().isEmpty()) {
						contratoPagamento.setCodigoTransacaoCielo(saleReturned.getPayment().getPaymentId());
					}
					if (saleReturned.getPayment().getStatus() != 1) {
						contrato.setStatus(Contrato.STATUS_PAGAMENTO_NAO_EFETUADO);
					}
					if (!saleReturned.getPayment().getReturnCode().equals("00")) {
						contrato.setStatus(Contrato.STATUS_PAGAMENTO_NAO_EFETUADO);
					}
				} catch (CieloRequestException e) {
					e.printStackTrace();
					contrato.setStatus(Contrato.STATUS_PAGAMENTO_COM_PROBLEMAS);
				} catch (IOException e) {
					e.printStackTrace();
					contrato.setStatus(Contrato.STATUS_PAGAMENTO_COM_PROBLEMAS);
				}
			}
		}`

**Comment by fernandohls** [comment]
O JSON que está sendo enviado é: 

```
{  
   "MerchantOrderId":"840a2a63785448564e43889d24c2d120",
   "Customer":{  
      "Name":"JOSÉ CUSTOMER",
      "Email":"josecustomer@email.com"
   },
   "Payment":{  
      "Installments":1,
      "Capture":false,
      "Authenticate":false,
      "Recurrent":false,
      "CreditCard":{  
         "CardNumber":"0000000000000001",
         "Holder":"JOSÉ",
         "ExpirationDate":"0518",
         "SecurityCode":"123",
         "SaveCard":false,
         "Brand":"Visa"
      },
      "SoftDescriptor":"compraOnline",
      "Provider":"Simulado",
      "Type":"CreditCard",
      "Amount":100
   }
}
```

**Comment by fernandohls** [comment]
Consegui resolver...

Não sei exatamente do que se trata, mas aparentemente é alguma inconsistência entre o JSON que eu estava enviando e o StringEntity usado na classe CreateSaleRequest.

Alterei todos os meus métodos para usar um EntityBuilder no lugar de StringEntity e deu certo.

```
@Override
public Sale execute(Sale param) throws IOException, CieloRequestException {

	String url = environment.getApiUrl() + "1/sales/";

	HttpPost request = new HttpPost(url);
	EntityBuilder entityBuilder = EntityBuilder.create();
	entityBuilder.setContentType(ContentType.APPLICATION_JSON);
	entityBuilder.setContentEncoding("UTF-8");
	entityBuilder.setText(GSONConverter.toJSON(param));
	request.setEntity(entityBuilder.build());

	HttpResponse response = sendRequest(request);

	return readResponse(response, Sale.class);
}

```
