### ISSUE TITLE
Pagamento com cartão de débito: adicionar parâmetros na URL de retorno Payment.ReturnUrl

### ISSUE THREAD

**Issue by nascimento-ecommet** [DeveloperCielo/API-3.0-Java#23]
Neto, seria possível para você adicionar parâmetros na minha url de callback (URI para onde o usuário será redirecionado após o fim do pagamento) a fim de indicar se a operação foi ou não realizada com sucesso?

Por exemplo, defino a minha url de callback da seguinte maneira: http://dominio.com?id=123456&param1={param1}&param2={param2}

Então no momento em que você for realizar o redirecionamento seria adicionado na minha url os parâmetros _param1_ e _param2_ que seriam identificados de maneira dinâmica, como por exemplo, Status ou ReturnCode

**Comment by nascimento-ecommet** [comment]
Olá Neto,
é possível ter esse tipo de informação na url de retorno?

**Comment by netojoaobatista** [comment]
Isso não é possível, @nascimento-ecommet; se precisa de informações de status após uma autenticação, você pode utilizar o método de consulta.

**Comment by nascimento-ecommet** [comment]
Neto, para finalizar, então quando a minha aplicação receber a notificação de retorno eu devo utilizar a operação de consulta para verificar o status da operação mesmo essa operação ter sido iniciada para pagamento por cartão de débito?

**Comment by netojoaobatista** [comment]
Quando o cliente escolher pagar com débito, sua aplicação precisará redirecioná-lo para o ambiente de autenticação do banco; depois de autenticado, ele será redirecionado de volta para sua url de retorno; nesse momento você utiliza a consulta para verificar o status da autorização e autenticação.

**Comment by nascimento-ecommet** [comment]
Entendi, a operação de consulta seria esta aqui da documentação?
[Consultando uma venda](http://developercielo.github.io/Webservice-3.0/#consultando-uma-venda)

Estou perguntando para confirmar porque tem uma indicação para operações realizadas com cartão de crédito.

Agradeço pelos esclarecimentos.

**Comment by netojoaobatista** [comment]
Correto; quando você criar a transação, você receberá um `paymentId`; após fazer o redirecionamento do cliente, você utiliza esse `paymentId` para fazer a consulta, fazendo um `GET /1/sales/{PaymentId}`.

**Comment by nascimento-ecommet** [comment]
Neto, 
Muito obrigado pelas orientações. Vou seguir com o desenvolvimento.
