### ISSUE TITLE
Integração com Maven

### ISSUE THREAD

**Issue by marcosrodriigues** [DeveloperCielo/API-3.0-Java#30]
Boa noite,

Estou com problema para integrar o meu sistema com a API 3.0.

Meu pom.xml:
```
<dependency>
	    	<groupId>br.cielo.cieloecommerc</groupId>
	    	<artifactId>api30.sdk</artifactId>
	    	<version>0.0.1-SNAPSHOT</version>
	    </dependency>
```

E o erro:
Missing artifact br.cielo.cieloecommerc:api30.sdk:0.0.1-SNAPSHOT

![image](https://user-images.githubusercontent.com/4214434/39162390-a6ed506c-474b-11e8-8c32-b3defcf28e19.png)

Alguém pode ajudar? :)

**Comment by eapmartins** [comment]
No seu .m2 existe este artefato?

Caso não exista, execute `mvn clean install` no diretório`/github/API-3.0-Java/api30.sdk` onde está presente o pom.xml

Depois procure no seu .m2 se ele foi gerado, deverá ter essa estrutura:
**.m2\repository\br\cielo\cieloecommerce\api30.sdk**

**Comment by frekele** [comment]
Conforme a issue https://github.com/DeveloperCielo/API-3.0-Java/issues/12 não existe artefato disponível no maven central, o que chega a ser uma piada.
Então você precisa compilar o projeto localmente e então usar a dependência.

Eu estou construindo meu próprio componente, caso tenha interesse em fazer fork, PR, contribuir ou usar https://github.com/frekele/cielo-ecommerce-client 
Ele ainda não está pronto para o uso, mas o https://github.com/frekele/cielo-lio-remote-client já está funcionando em produção.

**Comment by marcosrodriigues** [comment]
Obrigado pelas respostas pessoal.

Acabou que migrei para outra plataofrma de pagamento e consegui resolver o que eu queria!

@frekele vou dar uma olhada no seu componente, talvez eu entre com você, caso eu precise trabalhar novamente com pagamentos online.
