### ISSUE TITLE
Como testar o sandobox ?

### ISSUE THREAD

**Issue by alexjosesilva** [DeveloperCielo/API-3.0-Java#46]
Passei a url porém não trás nenhum dado

**url**
Tenho esta url: https://apiquerysandbox.cieloecommerce.cielo.com.br/1/sales/{1}

**Imagem:**
![image](https://user-images.githubusercontent.com/246117/44228267-4a9a5100-a16b-11e8-80e7-c6f7a2303cb5.png)

**Comment by frekele** [comment]
@alexjosesilva ,

acredito que você seja novo na área de TI, então com todo o respeito, sugiro que estude antes protocolos http, rest, design patterns e etc., antes de utilizar a SDK ou a API da cielo, ela não foi feita para quem não tem conhecimentos base em desenvolvimento de software.

Você está inundando nosso servidor de emails com essas perguntas que não tem relação alguma com a Cielo. Duvidas de programação e outros sugiro participar diretamente de um fórum como https://stackoverflow.com/ ou http://www.guj.com.br/

Vou lhe ajudar somente desta vez, você deve substituir a variavel {1} da url pelo valor desejado no request.

O manual explica muito bem isso.
https://developercielo.github.io/manual/cielo-ecommerce

😞

**Comment by alexjosesilva** [comment]
Foi realizado a substituição porém

POST
https://apiquerysandbox.cieloecommerce.cielo.com.br/1/sales/123

![image](https://user-images.githubusercontent.com/246117/44230471-9bad4380-a171-11e8-8258-5f6857b26dd1.png)

**Comment by frekele** [comment]
Como eu disse você precisa primeiro entender o básico de HTTP, quando você entender vai ver o quão 'boba' é a pergunta.

Sugiro começar por aqui:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview

**Comment by alexjosesilva** [comment]
Apartir do manual, esperava exibir este resultado:

![image](https://user-images.githubusercontent.com/246117/44231906-fe084300-a175-11e8-8d1a-c5cf8d43af41.png)

**Comment by alexjosesilva** [comment]
Infelizmente o manual é limitado.

**Comment by frekele** [comment]
O manual é bem completo, você que está informando campos errados em requisições erradas ,POST/PUT/DELETE/GET.

**Comment by alexjosesilva** [comment]
Em meu projeto inicial tinha importando como projeto Maven e estava utilizando o sdk puro. E apartir disso estava realizando as tentativas de conexão.

**Comment by alexjosesilva** [comment]
Tenho de criar uma app Rest no spring boot e inserir o skd do api.cielo para utilizar como recurso na aplicação
