### ISSUE TITLE
Consulta de parcelamento (Compra com cartão de crédito)

### ISSUE THREAD

**Issue by gabriel-ecommet** [DeveloperCielo/API-3.0-Java#5]
Olá,
Estou desenvolvendo o fluxo de compra com cartão de crédito, porém não encontrei na SDK serviços para consulta de parcelamento das compras com cartão, o que é imprescindível para a loja funcionar adequadamente. Existe alguma forma de consultar parcelamento? Mesmo que ainda não tenha na SDK, existe algum endpoint onde eu possa consultar essa informação mesmo que manualmente?

**Comment by netojoaobatista** [comment]
Não compreendi; como assim, consultar parcelamento?

Você consegue consultar o **pagamento** através do `paymentId`.

**Comment by gabriel-ecommet** [comment]
Consultar as condições de parcelamento, dado um valor de compra e uma bandeira de cartão. 
Ex: Uma compra no valor de R$ 100,00, utilizando um cartão Visa, consultaria as condições de parcelamento para exibir no meu formulário de pagamento:

R$ 100,00 à vista
R$ 102,50 em 2x de R$ 51,25 (com juros)
R$ 104,10 em 3x de R$ 34,70 (com juros)
...

Serviços como Mercado Pago ou BCash oferecem essa consulta, seus clientes vendedores podem oferecer condições diferenciadas de parcelamento ( absorvendo os juros até a 3ª parcela, por exemplo ). A quantidade de parcelas máxima também costumam variar de acordo com a bandeira do cartão. Também não achei na documentação nem a SDK a relação de bandeiras de cartão disponíveis, e suas respectivas referências pra se usar no objeto do pagamento.

Eu não sou cliente Cielo, estou apenas desenvolvendo, então não conheço muito bem ainda o produto.

**Comment by netojoaobatista** [comment]
Especificamente sobre o parcelamento, você pode definir o `Payment.Interest` como *ByMerchant* ou *ByIssuer*, para que o parcelamento ocorra pela loja ou pelo emissor, respectivamente.

**Comment by gabriel-ecommet** [comment]
Certo, então suponho que ByMerchant, seriam cobrados os juros de acordo com as condições do cliente definidas na Cielo, e ByIssuer, os juros serão cobrados de acordo com as taxas do emissor. 

O meu problema é que nosso produto gerencia diversas lojas virtuais pra diferentes vendedores, então não consigo fixar as parcelas de forma genérica pra todos os nossos clientes.  Existe uma previsão para o desenvolvimento de uma consulta de condições de parcelamento? Caso o contrário eu precisaria que cada cliente replicasse as condições de parcelamento dele sempre que tiver alguma alteração, o que pioraria muito a experiência dos nossos vendedores e tornando muito menos atraente a escolha pelo gateway de pagamento da Cielo, já que para os nosso outros gateways de pagamento isso é transparente / automático;
