### ISSUE TITLE
Configurar environment no CieloEcommerce

### ISSUE THREAD

**Issue by VictorMonte** [DeveloperCielo/API-3.0-Java#59]
Ola,

Gostaria de passar um endpoint para a classe CieloEcommerce para fins de mock.
Como poderia realizar essa configuracao? Hoje, apenas é possivel passar um enum Environment com Sandbox ou Production.

Esse seria uma instancia para sandbox
```new CieloEcommerce(merchant, Environment.Sandbox)```

**Comment by VictorMonte** [comment]
Tenho uma ideia de improvement.
Alterar o **enum** Environment para uma **classe** com fields static de production e sandbox.
Essa solucao **nao quebra o codigo** e habilita adicao de novos environments para o uso do cliente.

Se quiser posso fazer o PR para isto. 👍

**Comment by frekele** [comment]
@VictorMonte 
essa sdk está largada, se você verificar não existe update desde '14 Jul 2017' 
commit: https://github.com/DeveloperCielo/API-3.0-Java/commit/cf9fc25b6e70dfb6807f5313e238a58fc8edda65

Sugiro você criar seu próprio componente seguindo a documentação, a maioria dos devs criam o seu ou consomem a API diretamente.
outro detalhe, o suporte ao desenvolvedor é extremamente de baixa qualidade.
Parece que existem somente alguns privilegiados que recebem uma atenção especial, conforme vários relatos na internet.

**Comment by VictorMonte** [comment]
@frekele 

Omg! Obrigado por avisar.
Vou repassar para as pessoas isso.
Muitos estao pensando que esta ativa essa SDK.
